# Project Overview
This project implements a content-based book recommendation system using Natural Language Processing techniques to analyze book descriptions and metadata, providing personalized book suggestions based on textual similarity and content analysis.
Key Technologies & Approaches:

    1. Bag of Words Model: Implemented using Count Vectorizer and TF-IDF Vectorizer
    2. Similarity Measurement: Cosine similarity for finding related books
    3. Web Application: Interactive interface built with Streamlit
    4. Content-Based Filtering: Recommends books based on intrinsic features rather than user ratings

In [1]:
import pandas as pd 
import numpy as np 
import plotly.express as px

In [2]:
pd.set_option("display.max_rows",None)
pd.set_option("display.max_columns",None)

In [3]:
df = pd.read_csv("Books_dataset.csv")
df.head()

,bookId,title,series,author,rating,description,language,isbn,genres,characters,bookFormat,edition,pages,publisher,publishDate,firstPublishDate,awards,numRatings,ratingsByStars,likedPercent,setting,coverImg,bbeScore,bbeVotes,price
0,2767052-the-hunger-games,The Hunger Games,The Hunger Games #1,Suzanne Collins,4.33,WINNING MEANS FAME AND FORTUNE.LOSING MEANS CE...,English,9780439023481,"['Young Adult', 'Fiction', 'Dystopia', 'Fantas...","['Katniss Everdeen', 'Peeta Mellark', 'Cato (H...",Hardcover,First Edition,374,Scholastic Press,09/14/08,NaN,['Locus Award Nominee for Best Young Adult Boo...,6376780,"['3444695', '1921313', '745221', '171994', '93...",96.0,"['District 12, Panem', 'Capitol, Panem', 'Pane...",https://i.gr-assets.com/images/S/compressed.ph...,2993816,30516,5.09
1,2.Harry_Potter_and_the_Order_of_the_Phoenix,Harry Potter and the Order of the Phoenix,Harry Potter #5,"J.K. Rowling, Mary GrandPré (Illustrator)",4.50,There is a door at the end of a silent corrido...,English,9780439358071,"['Fantasy', 'Young Adult', 'Fiction', 'Magic',...","['Sirius Black', 'Draco Malfoy', 'Ron Weasley'...",Paperback,US Edition,870,Scholastic Inc.,09/28/04,06/21/03,['Bram Stoker Award for Works for Young Reader...,2507623,"['1593642', '637516', '222366', '39573', '14526']",98.0,['Hogwarts School of Witchcraft and Wizardry (...,https://i.gr-assets.com/images/S/compressed.ph...,2632233,26923,7.38
2,2657.To_Kill_a_Mockingbird,To Kill a Mockingbird,To Kill a Mockingbird,Harper Lee,4.28,The unforgettable novel of a childhood in a sl...,English,9999999999999,"['Classics', 'Fiction', 'Historical Fiction', ...","['Scout Finch', 'Atticus Finch', 'Jem Finch', ...",Paperback,NaN,324,Harper Perennial Modern Classics,05/23/06,07/11/60,"['Pulitzer Prize for Fiction (1961)', 'Audie A...",4501075,"['2363896', '1333153', '573280', '149952', '80...",95.0,"['Maycomb, Alabama (United States)']",https://i.gr-assets.com/images/S/compressed.ph...,2269402,23328,NaN
3,1885.Pride_and_Prejudice,Pride and Prejudice,NaN,"Jane Austen, Anna Quindlen (Introduction)",4.26,Alternate cover edition of ISBN 9780679783268S...,English,9999999999999,"['Classics', 'Fiction', 'Romance', 'Historical...","['Mr. Bennet', 'Mrs. Bennet', 'Jane Bennet', '...",Paperback,"Modern Library Classics, USA / CAN",279,Modern Library,10/10/00,01/28/13,[],2998241,"['1617567', '816659', '373311', '113934', '767...",94.0,"['United Kingdom', 'Derbyshire, England (Unite...",https://i.gr-assets.com/images/S/compressed.ph...,1983116,20452,NaN
4,41865.Twilight,Twilight,The Twilight Saga #1,Stephenie Meyer,3.60,About three things I was absolutely positive.\...,English,9780316015844,"['Young Adult', 'Fantasy', 'Romance', 'Vampire...","['Edward Cullen', 'Jacob Black', 'Laurent', 'R...",Paperback,NaN,501,"Little, Brown and Company",09/06/06,10/05/05,"['Georgia Peach Book Award (2007)', 'Buxtehude...",4964519,"['1751460', '1113682', '1008686', '542017', '5...",78.0,"['Forks, Washington (United States)', 'Phoenix...",https://i.gr-assets.com/images/S/compressed.ph...,1459448,14874,2.1

In [4]:
print(df.columns)

Index(['bookId', 'title', 'series', 'author', 'rating', 'description',
       'language', 'isbn', 'genres', 'characters', 'bookFormat', 'edition',
       'pages', 'publisher', 'publishDate', 'firstPublishDate', 'awards',
       'numRatings', 'ratingsByStars', 'likedPercent', 'setting', 'coverImg',
       'bbeScore', 'bbeVotes', 'price'],
      dtype='object')

In [5]:
print(len(df.columns))

25

In [6]:
print(df.describe())

             rating    numRatings  likedPercent      bbeScore      bbeVotes
count  52478.000000  5.247800e+04  51856.000000  5.247800e+04  52478.000000
mean       4.021878  1.787865e+04     92.231545  1.984023e+03     22.529003
std        0.367146  1.039448e+05      5.990689  3.515314e+04    369.158541
min        0.000000  0.000000e+00      0.000000  0.000000e+00     -4.000000
25%        3.820000  3.410000e+02     90.000000  8.400000e+01      1.000000
50%        4.030000  2.307000e+03     94.000000  9.700000e+01      1.000000
75%        4.230000  9.380500e+03     96.000000  1.870000e+02      2.000000
max        5.000000  7.048471e+06    100.000000  2.993816e+06  30516.000000

We dont need all the columns for our recommendation system, so we are going to remove columns which or not adding value.

In [7]:
drop_columns = ['bookId','series','isbn','characters', 'bookFormat', 'edition','publisher', 'publishDate', 'firstPublishDate', 'awards','language','pages','likedPercent',
                'ratingsByStars','setting', 'coverImg','price']

In [8]:
df = df.drop(drop_columns, axis = 1)
df.head()

,title,author,rating,description,language,genres,pages,numRatings,likedPercent,bbeScore,bbeVotes
0,The Hunger Games,Suzanne Collins,4.33,WINNING MEANS FAME AND FORTUNE.LOSING MEANS CE...,English,"['Young Adult', 'Fiction', 'Dystopia', 'Fantas...",374,6376780,96.0,2993816,30516
1,Harry Potter and the Order of the Phoenix,"J.K. Rowling, Mary GrandPré (Illustrator)",4.50,There is a door at the end of a silent corrido...,English,"['Fantasy', 'Young Adult', 'Fiction', 'Magic',...",870,2507623,98.0,2632233,26923
2,To Kill a Mockingbird,Harper Lee,4.28,The unforgettable novel of a childhood in a sl...,English,"['Classics', 'Fiction', 'Historical Fiction', ...",324,4501075,95.0,2269402,23328
3,Pride and Prejudice,"Jane Austen, Anna Quindlen (Introduction)",4.26,Alternate cover edition of ISBN 9780679783268S...,English,"['Classics', 'Fiction', 'Romance', 'Historical...",279,2998241,94.0,1983116,20452
4,Twilight,Stephenie Meyer,3.60,About three things I was absolutely positive.\...,English,"['Young Adult', 'Fantasy', 'Romance', 'Vampire...",501,4964519,78.0,1459448,14874

In [9]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 52478 entries, 0 to 52477
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   title         52478 non-null  object
 1   author        52478 non-null  object
 2   rating        52478 non-null  float64
 3   description   51140 non-null  object
 4   language      48672 non-null  object
 5   genres        52478 non-null  object
 6   pages         50131 non-null  object
 7   numRatings    52478 non-null  int64
 8   likedPercent  51856 non-null  float64
 9   bbeScore      52478 non-null  int64
 10  bbeVotes      52478 non-null  int64
dtypes: float64(2), int64(3), object(6)
memory usage: 4.4+ MB
None

In [10]:
print(df.isna().sum())

title              0
author             0
rating             0
description     1338
language        3806
genres             0
pages           2347
numRatings         0
likedPercent     622
bbeScore           0
bbeVotes           0
dtype: int64

In [11]:
print(len(df))

52478

As we can see we are missing really low amount of data like max 4000 data. we can easly populate it with mean data or we can drop based on the amount of missing values, so in our next step we are going to handle missing Values.

In [12]:
#Since Description is something which can not be populated using mean or another values we are going to replace it with NA
df["description"] = df["description"].fillna("NA")

In [16]:
print(df.isna().sum())

title           0
author          0
rating          0
description     0
language        0
genres          0
pages           0
numRatings      0
likedPercent    0
bbeScore        0
bbeVotes        0
dtype: int64

In [17]:
pd.set_option("display.max_colwidth", None)

In [18]:
# As you can see the genres are wrapped inside of an array of string lets take care of it
import ast 
df["genres"] = df["genres"].apply(ast.literal_eval)

In [19]:
df["genres"] = df["genres"].apply(lambda x: ', '.join(x))

In [20]:
df.head(3)

,title,author,rating,description,language,genres,pages,numRatings,likedPercent,bbeScore,bbeVotes
0,The Hunger Games,Suzanne Collins,4.33,"WINNING MEANS FAME AND FORTUNE.LOSING MEANS CERTAIN DEATH.THE HUNGER GAMES HAVE BEGUN. . . .In the ruins of a place once known as North America lies the nation of Panem, a shining Capitol surrounded by twelve outlying districts. The Capitol is harsh and cruel and keeps the districts in line by forcing them all to send one boy and once girl between the ages of twelve and eighteen to participate in the annual Hunger Games, a fight to the death on live TV.Sixteen-year-old Katniss Everdeen regards it as a death sentence when she steps forward to take her sister's place in the Games. But Katniss has been close to dead before—and survival, for her, is second nature. Without really meaning to, she becomes a contender. But if she is to win, she will have to start making choices that weight survival against humanity and life against love.",English,"Young Adult, Fiction, Dystopia, Fantasy, Science Fiction, Romance, Adventure, Teen, Post Apocalyptic, Action",374,6376780,96.0,2993816,30516
1,Harry Potter and the Order of the Phoenix,"J.K. Rowling, Mary GrandPré (Illustrator)",4.50,"There is a door at the end of a silent corridor. And it’s haunting Harry Pottter’s dreams. Why else would he be waking in the middle of the night, screaming in terror?Harry has a lot on his mind for this, his fifth year at Hogwarts: a Defense Against the Dark Arts teacher with a personality like poisoned honey; a big surprise on the Gryffindor Quidditch team; and the looming terror of the Ordinary Wizarding Level exams. But all these things pale next to the growing threat of He-Who-Must-Not-Be-Named - a threat that neither the magical government nor the authorities at Hogwarts can stop.As the grasp of darkness tightens, Harry must discover the true depth and strength of his friends, the importance of boundless loyalty, and the shocking price of unbearable sacrifice.His fate depends on them all.",English,"Fantasy, Young Adult, Fiction, Magic, Childrens, Adventure, Audiobook, Middle Grade, Classics, Science Fiction Fantasy",870,2507623,98.0,2632233,26923
2,To Kill a Mockingbird,Harper Lee,4.28,"The unforgettable novel of a childhood in a sleepy Southern town and the crisis of conscience that rocked it, To Kill A Mockingbird became both an instant bestseller and a critical success when it was first published in 1960. It went on to win the Pulitzer Prize in 1961 and was later made into an Academy Award-winning film, also a classic.Compassionate, dramatic, and deeply moving, To Kill A Mockingbird takes readers to the roots of human behavior - to innocence and experience, kindness and cruelty, love and hatred, humor and pathos. Now with over 18 million copies in print and translated into forty languages, this regional story by a young Alabama woman claims universal appeal. Harper Lee always considered her book to be a simple love story. Today it is regarded as a masterpiece of American literature.",English,"Classics, Fiction, Historical Fiction, School, Literature, Young Adult, Historical, Novels, Read For School, High School",324,4501075,95.0,2269402,23328
3,Pride and Prejudice,"Jane Austen, Anna Quindlen (Introduction)",4.26,"Alternate cover edition of ISBN 9780679783268Since its immediate success in 1813, Pride and Prejudice has remained one of the most popular novels in the English language. Jane Austen called this brilliant work ""her own darling child"" and its vivacious heroine, Elizabeth Bennet, ""as delightful a creature as ever appeared in print."" The romantic clash between the opinionated Elizabeth and her proud beau, Mr. Darcy, is a splendid performance of civilized sparring. And Jane Austen's radiant wit sparkles as her characters dance a delicate quadrille of flirtation and intrigue, making this book the most superb comedy of manners of Regency England.",English,"Classics, Fiction, Romance, Historical Fiction, Literature, Historical, Novels, Historical Romance, Classic Literature, Adult",279,2998241,94.0,1983116,20452
4,Twilight,Stephenie Meyer,3.60,"About three things I was absolutely positive.\r\n\r\nFirst, Edward was a vampire.\r\n\r\nSecond, there was a part of him—and I didn't know how dominant that part might be—that thirsted for my blood.\r\n\r\nAnd third, I was unconditionally and irrevocably in love with him.\r\n\r\nDeeply seductive and extraordinarily suspenseful, Twilight is a love story with bite.",English,"Young Adult, Fantasy, Romance, Vampires, Fiction, Paranormal, Paranormal Romance, Supernatural, Teen, Urban Fantasy",501,4964519,78.0,1459448,14874

Now we have to deal with the author column. Below we will see what are the problem are in that columns and how we can solve them

In [21]:
len(df.groupby(df["author"]))

27853

As you can see we have around 28K of authors we should take a deep look inside of the column to get better understanding

In [22]:
df["author"][20:55]

20                                                                                                       Ray Bradbury
21                                                                                   Veronica Roth (Goodreads Author)
22                                                                                                    William Golding
23           William Shakespeare, Paul Werstine (Editor), Barbara A. Mowat (Editor), Paavo Emil Cajander (Translator)
24                       Paulo Coelho (Goodreads Author), Alan R. Clarke (Translator), James Noel Smith (Illustrator)
25                                                                      Fyodor Dostoyevsky, David McDuff (Translator)
26                                                                                                    Stephen Chbosky
27                                                                      F. Scott Fitzgerald, Francis Scott Fitzgerald
28                                                                                 Cassandra Clare (Goodreads Author)
29                                            Orson Scott Card, Stefan Rudnicki (Narrator), Harlan Ellison (Narrator)
30                                                                                Kathryn Stockett (Goodreads Author)
31                                                                                                    L.M. Montgomery
32                                                                          J.K. Rowling, Mary GrandPré (Illustrator)
33    Antoine de Saint-Exupéry, Richard Howard (Translator), Ivan Minatti (Translator), Nguyễn Thành Vũ (Illustrator)
34                                           E.B. White, Garth Williams (Illustrator), Rosemary Wells (Illustrations)
35                                                                                                     John Steinbeck
36                                                                              Audrey Niffenegger (Goodreads Author)
37                                                        Bram Stoker, Nina Auerbach (Editor), David J. Skal (Editor)
38                                                                                                      Aldous Huxley
39                                                               Gabriel García Márquez, Gregory Rabassa (Translator)
40                                                                                                      J.D. Salinger
41                                                                                                    William Goldman
42                                                                                    Rick Riordan (Goodreads Author)
43                                                                                            Frances Hodgson Burnett
44                                                                                 Khaled Hosseini (Goodreads Author)
45                                                                                                  Madeleine L'Engle
46                                                                                                 George R.R. Martin
47                            Mark Twain, Guy Cardwell (Notes), John Seelye (Introduction), Walter Trier (Ilustrator)
48                                                                                                       Alice Sebold
49                                                                                     S.E. Hinton (Goodreads Author)
50                                                                                                     Maurice Sendak
51                                                                                                          Dr. Seuss
52                                                     Homer, Robert Fagles (Translator), Bernard Knox (Introduction)
53                                                                                                        Yann Martel
54                                                             Charles Dickens, Richard Maxwell (Editor/Introduction)
Name: author, dtype: object

We've discovered that the author field often includes not just the author's name but also mentions of editors, illustrators, or even book titles. After research, we've identified that the first name listed typically refers to the main author. Additionally, in some entries, book titles appear in the bracket, which could introduce bias during model training. To ensure clean and consistent data, we will extract only the first name as the primary author and remove any unrelated or noisy information.

In [24]:
df["author_alone"] = df["author"].apply(lambda x : x.split(",")[0].strip() if isinstance(x,str) else x)

In [25]:
df.head()

,title,author,rating,description,language,genres,pages,numRatings,likedPercent,bbeScore,bbeVotes,author_alone
0,The Hunger Games,Suzanne Collins,4.33,"WINNING MEANS FAME AND FORTUNE.LOSING MEANS CERTAIN DEATH.THE HUNGER GAMES HAVE BEGUN. . . .In the ruins of a place once known as North America lies the nation of Panem, a shining Capitol surrounded by twelve outlying districts. The Capitol is harsh and cruel and keeps the districts in line by forcing them all to send one boy and once girl between the ages of twelve and eighteen to participate in the annual Hunger Games, a fight to the death on live TV.Sixteen-year-old Katniss Everdeen regards it as a death sentence when she steps forward to take her sister's place in the Games. But Katniss has been close to dead before—and survival, for her, is second nature. Without really meaning to, she becomes a contender. But if she is to win, she will have to start making choices that weight survival against humanity and life against love.",English,"Young Adult, Fiction, Dystopia, Fantasy, Science Fiction, Romance, Adventure, Teen, Post Apocalyptic, Action",374,6376780,96.0,2993816,30516,Suzanne Collins
1,Harry Potter and the Order of the Phoenix,"J.K. Rowling, Mary GrandPré (Illustrator)",4.50,"There is a door at the end of a silent corridor. And it’s haunting Harry Pottter’s dreams. Why else would he be waking in the middle of the night, screaming in terror?Harry has a lot on his mind for this, his fifth year at Hogwarts: a Defense Against the Dark Arts teacher with a personality like poisoned honey; a big surprise on the Gryffindor Quidditch team; and the looming terror of the Ordinary Wizarding Level exams. But all these things pale next to the growing threat of He-Who-Must-Not-Be-Named - a threat that neither the magical government nor the authorities at Hogwarts can stop.As the grasp of darkness tightens, Harry must discover the true depth and strength of his friends, the importance of boundless loyalty, and the shocking price of unbearable sacrifice.His fate depends on them all.",English,"Fantasy, Young Adult, Fiction, Magic, Childrens, Adventure, Audiobook, Middle Grade, Classics, Science Fiction Fantasy",870,2507623,98.0,2632233,26923,J.K. Rowling
2,To Kill a Mockingbird,Harper Lee,4.28,"The unforgettable novel of a childhood in a sleepy Southern town and the crisis of conscience that rocked it, To Kill A Mockingbird became both an instant bestseller and a critical success when it was first published in 1960. It went on to win the Pulitzer Prize in 1961 and was later made into an Academy Award-winning film, also a classic.Compassionate, dramatic, and deeply moving, To Kill A Mockingbird takes readers to the roots of human behavior - to innocence and experience, kindness and cruelty, love and hatred, humor and pathos. Now with over 18 million copies in print and translated into forty languages, this regional story by a young Alabama woman claims universal appeal. Harper Lee always considered her book to be a simple love story. Today it is regarded as a masterpiece of American literature.",English,"Classics, Fiction, Historical Fiction, School, Literature, Young Adult, Historical, Novels, Read For School, High School",324,4501075,95.0,2269402,23328,Harper Lee
3,Pride and Prejudice,"Jane Austen, Anna Quindlen (Introduction)",4.26,"Alternate cover edition of ISBN 9780679783268Since its immediate success in 1813, Pride and Prejudice has remained one of the most popular novels in the English language. Jane Austen called this brilliant work ""her own darling child"" and its vivacious heroine, Elizabeth Bennet, ""as delightful a creature as ever appeared in print."" The romantic clash between the opinionated Elizabeth and her proud beau, Mr. Darcy, is a splendid performance of civilized sparring. And Jane Austen's radiant wit sparkles as her characters dance a delicate quadrille of flirtation and intrigue, making this book the most superb comedy of manners of Regency England.",English,"Classics, Fiction, Romance, Historical Fiction, Literature, Historical, Novels, Historical Romance, Classic Literature, Adult",279,2998241,94.0,1983116,20452,Jane Austen
4,Twilight,Stephenie Meyer,3.60,"About three things I was absolutely positive.\r\n\r\nFirst, Edward was a vampire.\r\n\r\nSecond, there was a part of him—and I didn't know how dominant that part might be—that thirsted for my blood.\r\n\r\nAnd third, I was unconditionally and irrevocably in love with him.\r\n\r\nDeeply seductive and extraordinarily suspenseful, Twilight is a love story with bite.",English,"Young Adult, Fantasy, Romance, Vampires, Fiction, Paranormal, Paranormal Romance, Supernatural, Teen, Urban Fantasy",501,4964519,78.0,1459448,14874,Stephenie Meyer

In [26]:
df["author_alone"].value_counts().sum()

np.int64(51856)

In [27]:
print(len(df.groupby("author_alone")))

23156

In [28]:
df["author_alone"] = df["author_alone"].str.strip().str.lower()

In [29]:
print(len(df.groupby("author_alone")))

23151

In [30]:
df.head(3)

,title,author,rating,description,language,genres,pages,numRatings,likedPercent,bbeScore,bbeVotes,author_alone
0,The Hunger Games,Suzanne Collins,4.33,"WINNING MEANS FAME AND FORTUNE.LOSING MEANS CERTAIN DEATH.THE HUNGER GAMES HAVE BEGUN. . . .In the ruins of a place once known as North America lies the nation of Panem, a shining Capitol surrounded by twelve outlying districts. The Capitol is harsh and cruel and keeps the districts in line by forcing them all to send one boy and once girl between the ages of twelve and eighteen to participate in the annual Hunger Games, a fight to the death on live TV.Sixteen-year-old Katniss Everdeen regards it as a death sentence when she steps forward to take her sister's place in the Games. But Katniss has been close to dead before—and survival, for her, is second nature. Without really meaning to, she becomes a contender. But if she is to win, she will have to start making choices that weight survival against humanity and life against love.",English,"Young Adult, Fiction, Dystopia, Fantasy, Science Fiction, Romance, Adventure, Teen, Post Apocalyptic, Action",374,6376780,96.0,2993816,30516,suzanne collins
1,Harry Potter and the Order of the Phoenix,"J.K. Rowling, Mary GrandPré (Illustrator)",4.50,"There is a door at the end of a silent corridor. And it’s haunting Harry Pottter’s dreams. Why else would he be waking in the middle of the night, screaming in terror?Harry has a lot on his mind for this, his fifth year at Hogwarts: a Defense Against the Dark Arts teacher with a personality like poisoned honey; a big surprise on the Gryffindor Quidditch team; and the looming terror of the Ordinary Wizarding Level exams. But all these things pale next to the growing threat of He-Who-Must-Not-Be-Named - a threat that neither the magical government nor the authorities at Hogwarts can stop.As the grasp of darkness tightens, Harry must discover the true depth and strength of his friends, the importance of boundless loyalty, and the shocking price of unbearable sacrifice.His fate depends on them all.",English,"Fantasy, Young Adult, Fiction, Magic, Childrens, Adventure, Audiobook, Middle Grade, Classics, Science Fiction Fantasy",870,2507623,98.0,2632233,26923,j.k. rowling
2,To Kill a Mockingbird,Harper Lee,4.28,"The unforgettable novel of a childhood in a sleepy Southern town and the crisis of conscience that rocked it, To Kill A Mockingbird became both an instant bestseller and a critical success when it was first published in 1960. It went on to win the Pulitzer Prize in 1961 and was later made into an Academy Award-winning film, also a classic.Compassionate, dramatic, and deeply moving, To Kill A Mockingbird takes readers to the roots of human behavior - to innocence and experience, kindness and cruelty, love and hatred, humor and pathos. Now with over 18 million copies in print and translated into forty languages, this regional story by a young Alabama woman claims universal appeal. Harper Lee always considered her book to be a simple love story. Today it is regarded as a masterpiece of American literature.",English,"Classics, Fiction, Historical Fiction, School, Literature, Young Adult, Historical, Novels, Read For School, High School",324,4501075,95.0,2269402,23328,harper lee

In [31]:
(df["author_alone"] == "j. k. rowling").sum()

np.int64(0)

In [32]:
# now lets take care of the titles inside of the brackets 
df["author_alone"] = df["author_alone"].apply(lambda x : x.split("(")[0].strip() if isinstance(x,str) else x)

In [33]:
df["author_alone"] = df["author_alone"].astype("string")

In [34]:
df["author_alone"][20:55]

20                ray bradbury
21               veronica roth
22             william golding
23         william shakespeare
24                paulo coelho
25          fyodor dostoyevsky
26             stephen chbosky
27         f. scott fitzgerald
28             cassandra clare
29            orson scott card
30            kathryn stockett
31             l.m. montgomery
32                j.k. rowling
33    antoine de saint-exupéry
34                  e.b. white
35              john steinbeck
36          audrey niffenegger
37                 bram stoker
38               aldous huxley
39      gabriel garcía márquez
40               j.d. salinger
41             william goldman
42                rick riordan
43     frances hodgson burnett
44             khaled hosseini
45           madeleine l'engle
46          george r.r. martin
47                  mark twain
48                alice sebold
49                 s.e. hinton
50              maurice sendak
51                   dr. seuss
52                       homer
53                 yann martel
54             charles dickens
Name: author_alone, dtype: string

In [35]:
print(len(df.groupby("author_alone")))

22861

In [36]:
df.columns

Index(['title', 'author', 'rating', 'description', 'language', 'genres',
       'pages', 'numRatings', 'likedPercent', 'bbeScore', 'bbeVotes',
       'author_alone'],
      dtype='object')

Let visualize some key features to understand the data set better

In [38]:
top_10_liked_books = df.sort_values(by="likedPercent", ascending = False).head(10)

In [39]:
top_10_liked_books["likedPercent"].value_counts()

likedPercent
100.0    10
Name: count, dtype: int64

In [40]:
fig = px.bar(
    top_10_liked_books,
    x="likedPercent",
    y="author_alone",
    color="title", 
    orientation='h',
    title="Top 10 Most Liked Books by Author",
    labels={"author_alone": "Author", "likedPercent": "Liked Percentage", "title": "Book Title"}
)

fig.update_layout(yaxis=dict(autorange="reversed"))
fig.show()

Let see which book have highest BBE-Score (Best Book Ever) and there authors

In [41]:
top_10_bbescore = df.sort_values(by="bbeScore", ascending = False).head(10)

In [42]:
fig = px.scatter(
    top_10_bbescore,
    x="bbeScore",
    y="title",
    color="author_alone", 
    orientation='h',
    title="Top 10 Most Liked Books by Author",
    labels={"author_alone" : "Author", "BBE-Score" : "bbeScore", "title" : "Book Title"}
)

fig.update_layout(
    yaxis=dict(autorange="reversed"),
)
fig.show()

Now lets find which book has the most rating

In [43]:
most_rating = df.sort_values(by = "rating", ascending = False).head(10)

In [45]:
fig  = px.box(
    most_rating,
    x="rating",
    y="author_alone",
    color = "title",
    orientation = "v",
    title = "Most rated books and their author",
    labels = {"author_alone" : "Author", "title" : "Books Title" , "rating" : "Rating"}
)

fig.update_layout(
    yaxis=dict(autorange="reversed")
)
fig.show()

Lets find how many language books are available and there frequency

In [46]:
print(df["language"].value_counts().sort_values(ascending=False).head(10))

language
English       42296
Unknow         3626
Arabic         1035
Spanish         682
French          573
German          506
Indonesian      366
Portuguese      359
Italian         249
Dutch           214
Name: count, dtype: int64

In [47]:
df.columns

Index(['title', 'author', 'rating', 'description', 'language', 'genres',
       'pages', 'numRatings', 'likedPercent', 'bbeScore', 'bbeVotes',
       'author_alone'],
      dtype='object')

# To build the recommendation system we have to select the important features. In next step we will list which features we are going to use and why.
    Title: While the title itself doesn't contribute meaningfully to the recommendation logic or similarity calculations, it remains essential for display purposes when presenting recommendations to users.
    
    Author: The author can help generate recommendations by identifying books written by the same person. This is especially useful for users who prefer following specific authors and want to explore more of their work.
    
    Description: The book description provides valuable semantic information about the content. It can be leveraged using NLP techniques (like TF-IDF or embeddings) to recommend books with similar narratives, themes, or styles. It enhances contextual recommendations beyond structured features.
    
    Genres: Genres are one of the most critical features for recommendations. Books within similar genres tend to align with user preferences (e.g., mystery, fantasy, romance). Genre-based filtering or similarity scoring can directly match user tastes.

In [48]:
req_feature = df[["author_alone","description","title","genres"]]
req_feature = req_feature.rename(columns = {"author_alone"  : "Author"})

In [49]:
req_feature["genres"] = req_feature["genres"].apply(lambda x:x.split(","))

In [50]:
req_feature["description"] = req_feature["description"].apply(lambda x:x.split())

In [51]:
req_feature["genres"] = req_feature["genres"].apply(lambda x : [ i.replace(" " , "") for i in x])

In [52]:
req_feature["Author"] = req_feature["Author"].apply(
    lambda x: x if isinstance(x, list) else [x] if pd.notnull(x) else []
)

In [53]:
req_feature["Author"] = req_feature["Author"].apply(lambda x: [ i.replace(" ", "") for i in x])
req_feature.head(3)

,Author,rating,description,title,genres,bbeScore
0,[suzannecollins],4.33,"[WINNING, MEANS, FAME, AND, FORTUNE.LOSING, MEANS, CERTAIN, DEATH.THE, HUNGER, GAMES, HAVE, BEGUN., ., ., .In, the, ruins, of, a, place, once, known, as, North, America, lies, the, nation, of, Panem,, a, shining, Capitol, surrounded, by, twelve, outlying, districts., The, Capitol, is, harsh, and, cruel, and, keeps, the, districts, in, line, by, forcing, them, all, to, send, one, boy, and, once, girl, between, the, ages, of, twelve, and, eighteen, to, participate, in, the, annual, Hunger, Games,, a, fight, to, the, death, on, live, TV.Sixteen-year-old, Katniss, Everdeen, regards, it, as, a, death, sentence, when, she, steps, forward, to, take, her, sister's, place, ...]",The Hunger Games,"[YoungAdult, Fiction, Dystopia, Fantasy, ScienceFiction, Romance, Adventure, Teen, PostApocalyptic, Action]",2993816
1,[j.k.rowling],4.50,"[There, is, a, door, at, the, end, of, a, silent, corridor., And, it’s, haunting, Harry, Pottter’s, dreams., Why, else, would, he, be, waking, in, the, middle, of, the, night,, screaming, in, terror?Harry, has, a, lot, on, his, mind, for, this,, his, fifth, year, at, Hogwarts:, a, Defense, Against, the, Dark, Arts, teacher, with, a, personality, like, poisoned, honey;, a, big, surprise, on, the, Gryffindor, Quidditch, team;, and, the, looming, terror, of, the, Ordinary, Wizarding, Level, exams., But, all, these, things, pale, next, to, the, growing, threat, of, He-Who-Must-Not-Be-Named, -, a, threat, that, neither, the, magical, government, nor, the, authorities, at, ...]",Harry Potter and the Order of the Phoenix,"[Fantasy, YoungAdult, Fiction, Magic, Childrens, Adventure, Audiobook, MiddleGrade, Classics, ScienceFictionFantasy]",2632233
2,[harperlee],4.28,"[The, unforgettable, novel, of, a, childhood, in, a, sleepy, Southern, town, and, the, crisis, of, conscience, that, rocked, it,, To, Kill, A, Mockingbird, became, both, an, instant, bestseller, and, a, critical, success, when, it, was, first, published, in, 1960., It, went, on, to, win, the, Pulitzer, Prize, in, 1961, and, was, later, made, into, an, Academy, Award-winning, film,, also, a, classic.Compassionate,, dramatic,, and, deeply, moving,, To, Kill, A, Mockingbird, takes, readers, to, the, roots, of, human, behavior, -, to, innocence, and, experience,, kindness, and, cruelty,, love, and, hatred,, humor, and, pathos., Now, with, over, 18, million, copies, in, print, and, ...]",To Kill a Mockingbird,"[Classics, Fiction, HistoricalFiction, School, Literature, YoungAdult, Historical, Novels, ReadForSchool, HighSchool]",2269402
3,[janeausten],4.26,"[Alternate, cover, edition, of, ISBN, 9780679783268Since, its, immediate, success, in, 1813,, Pride, and, Prejudice, has, remained, one, of, the, most, popular, novels, in, the, English, language., Jane, Austen, called, this, brilliant, work, ""her, own, darling, child"", and, its, vivacious, heroine,, Elizabeth, Bennet,, ""as, delightful, a, creature, as, ever, appeared, in, print."", The, romantic, clash, between, the, opinionated, Elizabeth, and, her, proud, beau,, Mr., Darcy,, is, a, splendid, performance, of, civilized, sparring., And, Jane, Austen's, radiant, wit, sparkles, as, her, characters, dance, a, delicate, quadrille, of, flirtation, and, intrigue,, making, this, book, the, most, superb, comedy, of, manners, of, Regency, England.]",Pride and Prejudice,"[Classics, Fiction, Romance, HistoricalFiction, Literature, Historical, Novels, HistoricalRomance, ClassicLiterature, Adult]",1983116
4,[stepheniemeyer],3.60,"[About, three, things, I, was, absolutely, positive., First,, Edward, was, a, vampire., Second,, there, was, a, part, of, him—and, I, didn't, know, how, dominant, that, part, might, be—that, thirsted, for, my, blood., And, third,, I, was, unconditionally, and, irrevocably, in, love, with, him., Deeply, seductive, and, extraordinarily, suspenseful,, Twilight, is, a, love, story, with, bite.]",Twilight,"[YoungAdult, Fantasy, Romance, Vampires, Fiction, Paranormal, ParanormalRomance, Supernatural, Teen, UrbanFantasy]",1459448

In [54]:
req_feature["Tags"] = req_feature["Author"] + req_feature["description"] + req_feature["genres"]

In [55]:
req_feature.head(3)

,Author,rating,description,title,genres,bbeScore,Tags
0,[suzannecollins],4.33,"[WINNING, MEANS, FAME, AND, FORTUNE.LOSING, MEANS, CERTAIN, DEATH.THE, HUNGER, GAMES, HAVE, BEGUN., ., ., .In, the, ruins, of, a, place, once, known, as, North, America, lies, the, nation, of, Panem,, a, shining, Capitol, surrounded, by, twelve, outlying, districts., The, Capitol, is, harsh, and, cruel, and, keeps, the, districts, in, line, by, forcing, them, all, to, send, one, boy, and, once, girl, between, the, ages, of, twelve, and, eighteen, to, participate, in, the, annual, Hunger, Games,, a, fight, to, the, death, on, live, TV.Sixteen-year-old, Katniss, Everdeen, regards, it, as, a, death, sentence, when, she, steps, forward, to, take, her, sister's, place, ...]",The Hunger Games,"[YoungAdult, Fiction, Dystopia, Fantasy, ScienceFiction, Romance, Adventure, Teen, PostApocalyptic, Action]",2993816,"[suzannecollins, WINNING, MEANS, FAME, AND, FORTUNE.LOSING, MEANS, CERTAIN, DEATH.THE, HUNGER, GAMES, HAVE, BEGUN., ., ., .In, the, ruins, of, a, place, once, known, as, North, America, lies, the, nation, of, Panem,, a, shining, Capitol, surrounded, by, twelve, outlying, districts., The, Capitol, is, harsh, and, cruel, and, keeps, the, districts, in, line, by, forcing, them, all, to, send, one, boy, and, once, girl, between, the, ages, of, twelve, and, eighteen, to, participate, in, the, annual, Hunger, Games,, a, fight, to, the, death, on, live, TV.Sixteen-year-old, Katniss, Everdeen, regards, it, as, a, death, sentence, when, she, steps, forward, to, take, her, sister's, ...]"
1,[j.k.rowling],4.50,"[There, is, a, door, at, the, end, of, a, silent, corridor., And, it’s, haunting, Harry, Pottter’s, dreams., Why, else, would, he, be, waking, in, the, middle, of, the, night,, screaming, in, terror?Harry, has, a, lot, on, his, mind, for, this,, his, fifth, year, at, Hogwarts:, a, Defense, Against, the, Dark, Arts, teacher, with, a, personality, like, poisoned, honey;, a, big, surprise, on, the, Gryffindor, Quidditch, team;, and, the, looming, terror, of, the, Ordinary, Wizarding, Level, exams., But, all, these, things, pale, next, to, the, growing, threat, of, He-Who-Must-Not-Be-Named, -, a, threat, that, neither, the, magical, government, nor, the, authorities, at, ...]",Harry Potter and the Order of the Phoenix,"[Fantasy, YoungAdult, Fiction, Magic, Childrens, Adventure, Audiobook, MiddleGrade, Classics, ScienceFictionFantasy]",2632233,"[j.k.rowling, There, is, a, door, at, the, end, of, a, silent, corridor., And, it’s, haunting, Harry, Pottter’s, dreams., Why, else, would, he, be, waking, in, the, middle, of, the, night,, screaming, in, terror?Harry, has, a, lot, on, his, mind, for, this,, his, fifth, year, at, Hogwarts:, a, Defense, Against, the, Dark, Arts, teacher, with, a, personality, like, poisoned, honey;, a, big, surprise, on, the, Gryffindor, Quidditch, team;, and, the, looming, terror, of, the, Ordinary, Wizarding, Level, exams., But, all, these, things, pale, next, to, the, growing, threat, of, He-Who-Must-Not-Be-Named, -, a, threat, that, neither, the, magical, government, nor, the, authorities, ...]"
2,[harperlee],4.28,"[The, unforgettable, novel, of, a, childhood, in, a, sleepy, Southern, town, and, the, crisis, of, conscience, that, rocked, it,, To, Kill, A, Mockingbird, became, both, an, instant, bestseller, and, a, critical, success, when, it, was, first, published, in, 1960., It, went, on, to, win, the, Pulitzer, Prize, in, 1961, and, was, later, made, into, an, Academy, Award-winning, film,, also, a, classic.Compassionate,, dramatic,, and, deeply, moving,, To, Kill, A, Mockingbird, takes, readers, to, the, roots, of, human, behavior, -, to, innocence, and, experience,, kindness, and, cruelty,, love, and, hatred,, humor, and, pathos., Now, with, over, 18, million, copies, in, print, and, ...]",To Kill a Mockingbird,"[Classics, Fiction, HistoricalFiction, School, Literature, YoungAdult, Historical, Novels, ReadForSchool, HighSchool]",2269402,"[harperlee, The, unforgettable, novel, of, a, childhood, in, a, sleepy, Southern, town, and, the, crisis, of, conscience, that, rocked, it,, To, Kill, A, Mockingbird, became, both, an, instant, bestseller, and, a, critical, success, when, it, was, first, published, in, 1960., It, went, on, to, win, the, Pulitzer, Prize, in, 1961, and, was, later, made, into, an, Academy, Award-winning, film,, also, a, classic.Compassionate,, dramatic,, and, deeply, moving,, To, Kill, A, Mockingbird, takes, readers, to, the, roots, of, human, behavior, -, to, innocence, and, experience,, kindness, and, cruelty,, love, and, hatred,, humor, and, pathos., Now, with, over, 18, million, copies, in, print, ...]"

In [56]:
req_feature["Tags"] = req_feature["Tags"].apply(lambda x: " ".join(x))

In [57]:
new_df = req_feature[["title","Tags","rating","bbeScore"]]
new_df.head(3)

,title,Tags,rating,bbeScore
0,The Hunger Games,"suzannecollins WINNING MEANS FAME AND FORTUNE.LOSING MEANS CERTAIN DEATH.THE HUNGER GAMES HAVE BEGUN. . . .In the ruins of a place once known as North America lies the nation of Panem, a shining Capitol surrounded by twelve outlying districts. The Capitol is harsh and cruel and keeps the districts in line by forcing them all to send one boy and once girl between the ages of twelve and eighteen to participate in the annual Hunger Games, a fight to the death on live TV.Sixteen-year-old Katniss Everdeen regards it as a death sentence when she steps forward to take her sister's place in the Games. But Katniss has been close to dead before—and survival, for her, is second nature. Without really meaning to, she becomes a contender. But if she is to win, she will have to start making choices that weight survival against humanity and life against love. YoungAdult Fiction Dystopia Fantasy ScienceFiction Romance Adventure Teen PostApocalyptic Action",4.33,2993816
1,Harry Potter and the Order of the Phoenix,"j.k.rowling There is a door at the end of a silent corridor. And it’s haunting Harry Pottter’s dreams. Why else would he be waking in the middle of the night, screaming in terror?Harry has a lot on his mind for this, his fifth year at Hogwarts: a Defense Against the Dark Arts teacher with a personality like poisoned honey; a big surprise on the Gryffindor Quidditch team; and the looming terror of the Ordinary Wizarding Level exams. But all these things pale next to the growing threat of He-Who-Must-Not-Be-Named - a threat that neither the magical government nor the authorities at Hogwarts can stop.As the grasp of darkness tightens, Harry must discover the true depth and strength of his friends, the importance of boundless loyalty, and the shocking price of unbearable sacrifice.His fate depends on them all. Fantasy YoungAdult Fiction Magic Childrens Adventure Audiobook MiddleGrade Classics ScienceFictionFantasy",4.50,2632233
2,To Kill a Mockingbird,"harperlee The unforgettable novel of a childhood in a sleepy Southern town and the crisis of conscience that rocked it, To Kill A Mockingbird became both an instant bestseller and a critical success when it was first published in 1960. It went on to win the Pulitzer Prize in 1961 and was later made into an Academy Award-winning film, also a classic.Compassionate, dramatic, and deeply moving, To Kill A Mockingbird takes readers to the roots of human behavior - to innocence and experience, kindness and cruelty, love and hatred, humor and pathos. Now with over 18 million copies in print and translated into forty languages, this regional story by a young Alabama woman claims universal appeal. Harper Lee always considered her book to be a simple love story. Today it is regarded as a masterpiece of American literature. Classics Fiction HistoricalFiction School Literature YoungAdult Historical Novels ReadForSchool HighSchool",4.28,2269402

In [58]:
new_df["Tags"][0]

"suzannecollins WINNING MEANS FAME AND FORTUNE.LOSING MEANS CERTAIN DEATH.THE HUNGER GAMES HAVE BEGUN. . . .In the ruins of a place once known as North America lies the nation of Panem, a shining Capitol surrounded by twelve outlying districts. The Capitol is harsh and cruel and keeps the districts in line by forcing them all to send one boy and once girl between the ages of twelve and eighteen to participate in the annual Hunger Games, a fight to the death on live TV.Sixteen-year-old Katniss Everdeen regards it as a death sentence when she steps forward to take her sister's place in the Games. But Katniss has been close to dead before—and survival, for her, is second nature. Without really meaning to, she becomes a contender. But if she is to win, she will have to start making choices that weight survival against humanity and life against love. YoungAdult Fiction Dystopia Fantasy ScienceFiction Romance Adventure Teen PostApocalyptic Action"

In [59]:
new_df["Tags"] = new_df["Tags"].apply(lambda x : x.lower())

C:\Users\Asus\AppData\Local\Temp\ipykernel_23224\3820998520.py:1: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [60]:
new_df.head()

,title,Tags,rating,bbeScore
0,The Hunger Games,"suzannecollins winning means fame and fortune.losing means certain death.the hunger games have begun. . . .in the ruins of a place once known as north america lies the nation of panem, a shining capitol surrounded by twelve outlying districts. the capitol is harsh and cruel and keeps the districts in line by forcing them all to send one boy and once girl between the ages of twelve and eighteen to participate in the annual hunger games, a fight to the death on live tv.sixteen-year-old katniss everdeen regards it as a death sentence when she steps forward to take her sister's place in the games. but katniss has been close to dead before—and survival, for her, is second nature. without really meaning to, she becomes a contender. but if she is to win, she will have to start making choices that weight survival against humanity and life against love. youngadult fiction dystopia fantasy sciencefiction romance adventure teen postapocalyptic action",4.33,2993816
1,Harry Potter and the Order of the Phoenix,"j.k.rowling there is a door at the end of a silent corridor. and it’s haunting harry pottter’s dreams. why else would he be waking in the middle of the night, screaming in terror?harry has a lot on his mind for this, his fifth year at hogwarts: a defense against the dark arts teacher with a personality like poisoned honey; a big surprise on the gryffindor quidditch team; and the looming terror of the ordinary wizarding level exams. but all these things pale next to the growing threat of he-who-must-not-be-named - a threat that neither the magical government nor the authorities at hogwarts can stop.as the grasp of darkness tightens, harry must discover the true depth and strength of his friends, the importance of boundless loyalty, and the shocking price of unbearable sacrifice.his fate depends on them all. fantasy youngadult fiction magic childrens adventure audiobook middlegrade classics sciencefictionfantasy",4.50,2632233
2,To Kill a Mockingbird,"harperlee the unforgettable novel of a childhood in a sleepy southern town and the crisis of conscience that rocked it, to kill a mockingbird became both an instant bestseller and a critical success when it was first published in 1960. it went on to win the pulitzer prize in 1961 and was later made into an academy award-winning film, also a classic.compassionate, dramatic, and deeply moving, to kill a mockingbird takes readers to the roots of human behavior - to innocence and experience, kindness and cruelty, love and hatred, humor and pathos. now with over 18 million copies in print and translated into forty languages, this regional story by a young alabama woman claims universal appeal. harper lee always considered her book to be a simple love story. today it is regarded as a masterpiece of american literature. classics fiction historicalfiction school literature youngadult historical novels readforschool highschool",4.28,2269402
3,Pride and Prejudice,"janeausten alternate cover edition of isbn 9780679783268since its immediate success in 1813, pride and prejudice has remained one of the most popular novels in the english language. jane austen called this brilliant work ""her own darling child"" and its vivacious heroine, elizabeth bennet, ""as delightful a creature as ever appeared in print."" the romantic clash between the opinionated elizabeth and her proud beau, mr. darcy, is a splendid performance of civilized sparring. and jane austen's radiant wit sparkles as her characters dance a delicate quadrille of flirtation and intrigue, making this book the most superb comedy of manners of regency england. classics fiction romance historicalfiction literature historical novels historicalromance classicliterature adult",4.26,1983116
4,Twilight,"stepheniemeyer about three things i was absolutely positive. first, edward was a vampire. second, there was a part of him—and i didn't know how dominant that part might be—that thirsted for my blood. and third, i was unconditionally and irrevocably in love with him. deeply seductive and extraordinarily suspenseful, twilight is a love story with bite. youngadult fantasy romance vampires fiction paranormal paranormalromance supernatural teen urbanfantasy",3.60,1459448

In [61]:
import nltk

In [62]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [63]:
def stemming(text):
    stem = []
    for i in text.split():
        stem.append(ps.stem(i))
    return " ".join(stem)

In [64]:
new_df["Tags"] = new_df["Tags"].apply(stemming)

C:\Users\Asus\AppData\Local\Temp\ipykernel_23224\3586195072.py:1: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [65]:
new_df.head(3)

,title,Tags,rating,bbeScore
0,The Hunger Games,"suzannecollin win mean fame and fortune.los mean certain death.th hunger game have begun. . . .in the ruin of a place onc known as north america lie the nation of panem, a shine capitol surround by twelv outli districts. the capitol is harsh and cruel and keep the district in line by forc them all to send one boy and onc girl between the age of twelv and eighteen to particip in the annual hunger games, a fight to the death on live tv.sixteen-year-old katniss everdeen regard it as a death sentenc when she step forward to take her sister' place in the games. but katniss ha been close to dead before—and survival, for her, is second nature. without realli mean to, she becom a contender. but if she is to win, she will have to start make choic that weight surviv against human and life against love. youngadult fiction dystopia fantasi sciencefict romanc adventur teen postapocalypt action",4.33,2993816
1,Harry Potter and the Order of the Phoenix,"j.k.rowl there is a door at the end of a silent corridor. and it’ haunt harri pottter’ dreams. whi els would he be wake in the middl of the night, scream in terror?harri ha a lot on hi mind for this, hi fifth year at hogwarts: a defens against the dark art teacher with a person like poison honey; a big surpris on the gryffindor quidditch team; and the loom terror of the ordinari wizard level exams. but all these thing pale next to the grow threat of he-who-must-not-be-nam - a threat that neither the magic govern nor the author at hogwart can stop.a the grasp of dark tightens, harri must discov the true depth and strength of hi friends, the import of boundless loyalty, and the shock price of unbear sacrifice.hi fate depend on them all. fantasi youngadult fiction magic children adventur audiobook middlegrad classic sciencefictionfantasi",4.50,2632233
2,To Kill a Mockingbird,"harperle the unforgett novel of a childhood in a sleepi southern town and the crisi of conscienc that rock it, to kill a mockingbird becam both an instant bestsel and a critic success when it wa first publish in 1960. it went on to win the pulitz prize in 1961 and wa later made into an academi award-win film, also a classic.compassionate, dramatic, and deepli moving, to kill a mockingbird take reader to the root of human behavior - to innoc and experience, kind and cruelty, love and hatred, humor and pathos. now with over 18 million copi in print and translat into forti languages, thi region stori by a young alabama woman claim univers appeal. harper lee alway consid her book to be a simpl love story. today it is regard as a masterpiec of american literature. classic fiction historicalfict school literatur youngadult histor novel readforschool highschool",4.28,2269402
3,Pride and Prejudice,"janeausten altern cover edit of isbn 9780679783268sinc it immedi success in 1813, pride and prejudic ha remain one of the most popular novel in the english language. jane austen call thi brilliant work ""her own darl child"" and it vivaci heroine, elizabeth bennet, ""a delight a creatur as ever appear in print."" the romant clash between the opinion elizabeth and her proud beau, mr. darcy, is a splendid perform of civil sparring. and jane austen' radiant wit sparkl as her charact danc a delic quadril of flirtat and intrigue, make thi book the most superb comedi of manner of regenc england. classic fiction romanc historicalfict literatur histor novel historicalrom classicliteratur adult",4.26,1983116
4,Twilight,"stepheniemey about three thing i wa absolut positive. first, edward wa a vampire. second, there wa a part of him—and i didn't know how domin that part might be—that thirst for my blood. and third, i wa uncondit and irrevoc in love with him. deepli seduct and extraordinarili suspenseful, twilight is a love stori with bite. youngadult fantasi romanc vampir fiction paranorm paranormalrom supernatur teen urbanfantasi",3.60,1459448

In [66]:
new_df["Tags"][3455]

"johnsteinbeck while fulfil hi dead father' dream of creat a prosper farm in california, joseph wayn come to believ that a magnific tree on the farm embodi hi father' spirit. hi brother and their famili share in joseph' prosper and the farm flourish - until one brother, scare by joseph' pagan belief, kill the tree and bring diseas and famin on the farm. set in familiar steinbeck country, to a god unknown is a mystic tale, explor one man' attempt to control the forc of natur and to understand the way of god. fiction classic literatur american novel nobelpr literaryfict theunitedstatesofamerica historicalfict religion"

# Here we are going with Bag of Wrods Approach

 Lets go with countvector first

In [67]:
from sklearn.feature_extraction.text import CountVectorizer
# cv = CountVectorizer(max_features = 2000, stop_words = 'english')

In [68]:
# vectors = cv.fit_transform(new_df["Tags"])

In [69]:
# vectors.shape

In [70]:
# np.set_printoptions(threshold=np.inf)

In [71]:
# cv.get_feature_names_out()

In high-dimensional spaces, using Euclidean distance is often not ideal due to the "curse of dimensionality," which can cause distance values to become less meaningful. Instead, cosine similarity is generally preferred, as it focuses on the angle between vectors rather than their magnitude, making it more effective for measuring similarity in sparse or high-dimensional feature spaces (such as TF-IDF or embeddings).

In [72]:
from sklearn.metrics.pairwise import cosine_similarity
# similarity_matrix = cosine_similarity(vectors, dense_output=False)

In [73]:
# sim_matrix = similarity_matrix.toarray()

In [74]:
# sim_matrix.shape

In [110]:
# new_df.head()

In [111]:
# def recommendation(book_name):
#     book_index = new_df[new_df["title"] == book_name].index[0]
#     cosin_distance  = sim_matrix[book_index]
#     book_list = sorted(list(enumerate(cosin_distance)),reverse = True, key = lambda x:x[1])[1:6]
#     for book in book_list:
#         print(new_df.iloc[book[0]].title)

In [77]:
# recommendation("Troublesome Young Men: The Rebels Who Brought Churchill to Power and Helped Save England")

Since the CountVector approach did not went as we expected we are switching to Tf-Idf(that's why above code is commented)

In [78]:
new_df[new_df["title"] == "Troublesome Young Men: The Rebels Who Brought Churchill to Power and Helped Save England"].index[0]

np.int64(46002)

# After using the countVector we cant able to see any good recommendation. So we are now going to use TF-IDF.

In [79]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [80]:
tfidf = TfidfVectorizer(stop_words='english',
    ngram_range=(1, 2),
    max_df=0.8,
    min_df=2)

In [81]:
tfidf_matrix = tfidf.fit_transform(new_df["Tags"])

In [85]:
# Index map: title to row index
indices = pd.Series(new_df.index, index=new_df['title']).drop_duplicates()

def recommend_books(title, n=5):
    idx = indices[title]
    target_vec = tfidf_matrix[idx]
    sim_scores = cosine_similarity(target_vec, tfidf_matrix).flatten()
    sim_scores[idx] = 0  # Ignore self
    
    top_indices = sim_scores.argsort()[::-1]  # Sorted in descending order
    top_indices = top_indices[:n]  # Only take top N
    
    # Safety check: filter out invalid indices
    top_indices = [i for i in top_indices if i < len(new_df)]

    return new_df.iloc[top_indices][['title', 'rating']]

In [112]:
recommend_books("Harry Potter and the Sorcerer's Stone")

                                              title  rating
93         Harry Potter and the Prisoner of Azkaban    4.57
126         Harry Potter and the Chamber of Secrets    4.43
51722  Hogwarts: An Incomplete and Unreliable Guide    4.21
103             Harry Potter and the Goblet of Fire    4.56
2286                        Harry Potter Collection    4.73

In [95]:
new_df["title"][2444]

'Piercing'

# Using Pickle to serialize the books DataFrame and TF-IDF matrix for efficient loading in the Streamlit app

In [104]:
import pickle as pkl

In [107]:
pkl.dump(new_df.to_dict(),open("books_dict.pkl", "wb"))

In [108]:
pkl.dump(tfidf_matrix,open("tfidf_matrix.pkl","wb"))